### PR TITLE
fix keymap & make package usable

### PR DESCRIPTION
**Pull request by trev-dev**
I was unable to get this package working as-is while following the directions, so I spent a couple minutes debugging `main`.

- https://github.com/amno1/org-view-mode/commit/803b2690d7e99a3b6888df9862d413f5e71949ba#diff-af1203a6fff89e504352264af9df62ded956d9de93b6192a5187068f7dd19a85L176 This keymap was throwing a type error that prevented the package from loading, so I commented it out and refactored it. I only added `q` for quitting org-view-mode.
- Undefined function `org-view-hide-keywords-mode` was preventing me from being able to load the package.

I've tested it on my end after these changes and `org-view-mode` is now working.

### CODE REVIEW

**Comment by amno1** [comment]
> Undefined function org-view-hide-keywords-mode was preventing me from being able to load the package.

Yes, it was my bad. I have noticed that I somehow deleted an entire mode definition before I uploaded it. I was refactoring some code to make it more clean, so I must have either hit one undo too many, or I have forgotten to paste it back. I noticed myself this morning. The last commit has it back.

> This keymap was throwing a type error that prevented the package from loading

I see now, that defvar-keymap is added recently. It will be avialable in 29.1

```
defvar-keymap is a Lisp macro in ‘keymap.el’.

(defvar-keymap VARIABLE-NAME &key DOC FULL PARENT SUPPRESS NAME PREFIX KEYMAP
&rest [KEY DEFINITION]...)

Define VARIABLE-NAME as a variable with a keymap definition.
See ‘define-keymap’ for an explanation of the keywords and KEY/DEFINITION.

In addition to the keywords accepted by ‘define-keymap’, this
macro also accepts a ‘:doc’ keyword, which (if present) is used
as the variable documentation string.

  Other relevant functions are documented in the keymaps group.
  Probably introduced at or before Emacs version 29.1.

```
I'll add back old-style map declaration for compatibility.  Give me a bit of time to think of it, before I merge your fix or do something else regarding the keymap.

Thank you for the help!

**Comment by amno1** [comment]
I don't see this trailing-whitespace on my private either, so I must have changed it after I uploaded too. The last commit with commenting out keyword mode is fixed by adding the keyword mode definition back, it should not be commented out.

I have added the old-style map definition. All those keys (q, e, c) have to be defined since we run built-in view-mode which defines all of those, so we have to re-define them. If we don't, then it is possible to accidentally turn-off view-mode which will make buffer writable, but would not turn off the entire org-view-mode. That could potentially lead to confusion, so I think it is best to enable/disable all at once. That is the reason I re-define all those keys.

I have thoughts to make the org-view-mode partially writable, by turning on/off view-mode, but I haven't come to that yet.

I will close the PR for now, but thank you nonetheless for the help! I appreciate the interest and the effort.

**Comment by trev-dev** [comment]
> I see now, that defvar-keymap is added recently. It will be avialable in 29.1

Yeah 29 is 2 full point releases away from "stable" (27). Maybe we can use `emacs-version` to check which function to use.

I'm happy to help, it's a cool package :)

**Comment by amno1** [comment]
I don't think it's worth, I just re-wrote it as old macro def with let statement, it's not a big deal.

**Pull request closed without merging**
